### ISSUE TITLE
TypeError: Object(...) is not a function at FirebaseCrashlytics.initialise()

### ISSUE THREAD

**Issue by mattid89** [ReallySmallSoftware/cordova-plugin-firebase-crashlytics#38]
## Expected Behavior
It should initialize all crashlytics functionalities.

## Actual Behavior
when I execute the initialise() function, it result in an exception that crash the app:

```
ERROR
TypeError: Object(...) is not a function
message:"Object(...) is not a function"
ngDebugContext:DebugContext_ {view: Object, nodeIndex: 47, nodeDef: Object, …}
ngErrorLogger:function () { … }
stack:"TypeError: Object(...) is not a function
    at FirebaseCrashlytics.initialise (file:///android_asset/www/build/vendor.js:71737:136)
    at LoginPage.webpackJsonp.27.LoginPage.login (file:///android_asset/www/build/main.js:3429:15)
    at Object.eval [as handleEvent] (ng:///AppModule/LoginPage.ngfactory.js:85:35)
    at handleEvent (file:///android_asset/www/build/vendor.js:12331:138)
    at callWithDebugContext (file:///android_asset/www/build/vendor.js:13795:42)
    at Object.debugHandleEvent [as handleEvent] (file:///android_asset/www/build/vendor.js:13383:12)
    at dispatchEvent (file:///android_asset/www/build/vendor.js:8924:21)
    at file:///android_asset/www/build/vendor.js:9535:20
    at HTMLButtonElement.<anonymous> (file:///android_asset/www/build/vendor.js:32563:53)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:15660)"
```

## Steps to Reproduce the Problem
just implement the basic method

## Specifications

  - Plugin version:
            **cordova-plugin-firebase-crashlytics 0.0.6 "Cordova Firebase Crashlytics Plugin"**
            **cordova-support-google-services 1.4.1 "cordova-support-google-services"**

  - Framework version and more:

```
Ionic:

   Ionic CLI          : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4
   Cordova Plugins   : no whitelisted plugins (15 plugins total)
            cordova-plugin-camera 4.1.0 "Camera"
            cordova-plugin-compat 1.2.0 "Compat"
            cordova-plugin-console 1.1.0 "Console"
            cordova-plugin-device 1.1.7 "Device"
            cordova-plugin-file 6.0.2 "File"
            cordova-plugin-file-transfer 1.7.1 "File Transfer"
            cordova-plugin-filepath 1.5.8 "cordova-plugin-filepath"
            cordova-plugin-firebase-crashlytics 0.0.6 "Cordova Firebase Crashlytics Plugin"
            cordova-plugin-network-information 2.0.2 "Network Information"
            cordova-plugin-splashscreen 4.1.0 "Splashscreen"
            cordova-plugin-statusbar 2.4.3 "StatusBar"
            cordova-plugin-whitelist 1.3.4 "Whitelist"
            cordova-support-google-services 1.4.1 "cordova-support-google-services"
            ionic-plugin-keyboard 2.2.1 "Keyboard"
            phonegap-plugin-barcodescanner 8.1.0 "BarcodeScanner"

Utility:

   cordova-res : not installed
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/Users/matiasdoto/Library/Android/sdk)
   NodeJS            : v10.13.0 (/usr/local/bin/node)
   npm               : 6.14.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.6 Build version 11E708
```

**Comment by vibgup** [comment]
Hi @mattid89 

We are facing the same issue as well
Did you get a solution to the issue

**Comment by mattid89** [comment]
Hi @vibgup , unfortunately I couldn't get it. I've decided to use Sentri.io.
https://sentry.io/ 
It is not the same, but it solved my problem.

**Comment by Nikhil-Daffodil** [comment]
Have you got any solution to this?
